CallingRestApiFromController/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CallingRestApiFromController.Models
{
    public class Customer
    {
        public int id { get; set; }
        [Display(Name = "Customer Name")]
        public string name { get; set; }
        [Display(Name = "Customer Father Name")]
        public string fathername { get; set; }
        [Display(Name = "Customer Mother Name")]
        public string mothername { get; set; }
        [Display(Name = "Contact No")]
        public string phone { get; set; }
    }
}

CallingRestApiFromController/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallingRestApiFromController.Models
{
    public class Department
    {
        public int id { get; set; }
        public string deptCode { get; set; }
        public string deptName { get; set; }
    }
}

CallingRestApiFromController/Controllers/CustomerController.cs
using CallingRestApiFromController.Models;
using CallingRestApiFromController.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CallingRestApiFromController.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            CustomerClient customerClient = new CustomerClient();
            List<Customer> customers = customerClient.findAll().ToList();
            return View(customers);
        }
        public ActionResult Create()
        {
            Customer customer = new Customer();
            return View(customer);
        }
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            CustomerClient customerClient = new CustomerClient();
            bool result = customerClient.Create(customer);
            return RedirectToAction("Index");
        }
    }
}

CallingRestApiFromController/Controllers/DepartmentController.cs
using CallingRestApiFromController.Models;
using CallingRestApiFromController.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CallingRestApiFromController.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            DepartmentClient departmentClient = new DepartmentClient();
            List<Department> departments = departmentClient.findAll().ToList();
            return View(departments);
        }

        public ActionResult Create()
        {
            Department department = new Department();
            return View(department);
        }
        [HttpPost]
        public ActionResult Create(Department department)
        {
            DepartmentClient departmentClient = new DepartmentClient();
            departmentClient.Create(department);
            return RedirectToAction("Index");

        }
        public ActionResult Edit(int id)
        {
            DepartmentClient departmentClient = new DepartmentClient();
            Department department = departmentClient.find(id);
            return View("Edit", department);
        }
        [HttpPost]
        public ActionResult Edit(Department department)
        {
            DepartmentClient departmentClient = new DepartmentClient();
            bool result = departmentClient.Edit(department);
            if (result)
            {
                ViewBag.msg = "Department Edit Successfully!";
                return RedirectToAction("Index");
            }else
            {
                ViewBag.msg = "Error To Save Department!";
                return RedirectToAction("Edit", department);
            }
           
        }
        public ActionResult Delete(int id)
        {
            DepartmentClient departmentClient = new DepartmentClient();
            Department department = departmentClient.find(id);
            return View("Edit", department);
        }
        [HttpPost]
        public ActionResult Delete(Department department)
        {
            DepartmentClient departmentClient = new DepartmentClient();
            bool result = departmentClient.Delete(department.id);
            if (result)
            {
                ViewBag.msg = "Department Delete Successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.msg = "Error To Delete Department!";
                return RedirectToAction("Delete", department.id);
            }
        }
    }
}

CallingRestApiFromController/Controllers/HomeController.cs
using CallingRestApiFromController.Models;
using CallingRestApiFromController.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CallingRestApiFromController.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
        
    }
}

CallingRestApiFromController/Views/Customer/Create.cshtml
@model CallingRestApiFromController.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fathername, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fathername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fathername, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mothername, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mothername, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mothername, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CallingRestApiFromController/Views/Customer/Index.cshtml
@model List<CallingRestApiFromController.Models.Customer>
@{
    ViewBag.Title = "Index";
}
<h2>Show All Customers </h2>
@if (@ViewBag.msg != null)
{
    <h3>@ViewBag.msg</h3>
}
<table class="table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Customer Name</th>
            <th>Customer Father Name</th>
            <th>Customer Mother Name</th>
            <th>Contact No</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var customer in Model)
            {
            <tr>
                <td>@customer.id</td>
                <td>@customer.name</td>
                <td>@customer.fathername</td>
                <td>@customer.mothername</td>
                <td>@customer.phone</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = customer.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = customer.id })
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>
    </tbody>
</table>

CallingRestApiFromController/Views/Department/Create.cshtml
@model CallingRestApiFromController.Models.Department

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.deptCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CallingRestApiFromController/Views/Department/Delete.cshtml
@model CallingRestApiFromController.Models.Department

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.deptCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deptName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deptName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CallingRestApiFromController/Views/Department/Edit.cshtml
@model CallingRestApiFromController.Models.Department

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@if (@ViewBag.msg != null)
{
    <h3>@ViewBag.msg</h3>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.deptCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deptName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deptName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deptName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CallingRestApiFromController/Views/Department/Index.cshtml
@model List<CallingRestApiFromController.Models.Department>
@{
    ViewBag.Title = "Index";
}

<h2>Show All Departments </h2>
@if (@ViewBag.msg != null)
{
    <h3>@ViewBag.msg</h3>
}
<table class="table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Department Code</th>
            <th>Department Name</th>            
            <th>Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var department in Model)
            {
            <tr>
                <td>@department.id</td>
                <td>@department.deptCode</td>
                <td>@department.deptName</td>                
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = department.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = department.id })
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>
    </tbody>
</table>

CallingRestApiFromController/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CallingRestApiFromController/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>                    
                    <li>@Html.ActionLink("Index", "Index", "Department")</li>
                    <li>@Html.ActionLink("Create", "Create", "Department")</li>
                    <li>@Html.ActionLink("Index", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Create", "Create", "Customer")</li>                      
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>